// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Vacunas.mundo;

import java.util.ArrayList;

/************************************************************/
/**
 * clase que indica un departamento
 */
public class Departamento {
	/**
	 * nombre del departamento
	 */
	private String nombre;
	/**
	 * arraylist de municipios
	 */
	private ArrayList<Municipio> municipio;

///////////////////////////////constructor ////////////////////////////////////////

	/**
	 * construye un departamento
	 * @param municipio lista de municipios
	 * @param nombre nombre de departamento
	*/
	public Departamento(String nombre, ArrayList<Municipio>  municipio) {
		super();
		this.nombre = nombre;
		this.municipio = municipio;
	}


	/////////////////////////////// get y set ////////////////////////////////////////
	/**
	 * devuelve el nombre
	 * @return  el nombre
	*/
	public String getNombre() {
		return nombre;
	}
	/**
	 * modifica  el nombre 
	 * @param nombre el nombre
	*/
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	/**
	 * devuelve la lista de  municipios
	 * @return  la lista de  municipios
	*/
	public ArrayList<Municipio> getMunicipio() {
		return municipio;
	}
	/**
	 * añade un municipio 
	 * @param municipio el municipio
	*/
	public void setMunicipio(Municipio municipio) {
		this.municipio.add(municipio);
	}

	
	///////////////////////////////string  ////////////////////////////////////////
	/**
	 * devuelve una string con datos de la clase
	 * @return datos de esta clase
	*/
	@Override
	public String toString() {
		return "Departamento [nombre=" + nombre + ", municipio=" + municipio + "]";
	}
	
	
	
};
