// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Vacunas.mundo;

/************************************************************/
/**
 * clase que indica un municipio
 */
public class Municipio {
	/**
	 * nombre del municipio
	 */
	private String nombre;

///////////////////////////////constructor ////////////////////////////////////////
	/**
	 * construye un Municipio
	 * @param nombre nombre de Municipio
	*/
	public Municipio(String nombre) {
		super();
		this.nombre = nombre;
	}

	/////////////////////////////// get y set ////////////////////////////////////////
	/**
	 * devuelve el nombre
	 * @return  el nombre
	*/
	public String getNombre() {
		return nombre;
	}
	/**
	 * cambia el nombre
	 * @param nombre el nombre
	*/
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	///////////////////////////////string  ////////////////////////////////////////
	/**
	 * devuelve una string con datos de la clase
	 * @return datos de esta clase
	*/
	@Override
	public String toString() {
		return "Municipio [nombre=" + nombre + "]";
	}
		
	
};
