// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Vacunas.mundo;

/************************************************************/
/**
 * Clase que representa al usuario
 */
public class Usuario {
	/**
	 * identificacion del usuario
	 */
	private String id;
	/**
	 * nombres del usuario
	 */
	private String nombres;
	/**
	 * email del usuario
	 */
	private String email;
	/**
	 * tipoId del usuario
	 */
	private String tipoId;
	/**
	 * apellidos del usuario
	 */
	private String apellidos;
	/**
	 * celular del usuario
	 */
	private String celular;
	/**
	 * telefono del usuario
	 */
	private String telefono;
	/**
	 * departamento del usuario
	 */
	private Departamento departamento;
	/**
	 * municipio del usuario
	 */
	private Municipio municipio;
	/**
	 *  direccion del usuario
	 */
	private String direccion;
	
	
	
	///////////////////////////////constructor ////////////////////////////////////////
	
	/**
	 * construye un  usuario
	 * @param pId   identificacion del usuario
	 * @param pNombres   nombres del usuario
	 * @param pEmail    email del usuario
	 * @param pTipoId  tipo de identificacion del usuario
	 * @param pApellidos  apellidos del usuario
	 * @param Pcelular  celular del usuario
	 * @param pTelefono   telefono del usuario
	 * @param pDepartamento   departamento del usuario
	 * @param pMunicipio   municipio del usuario
	 * @param pDireccion   direccion del usuario
	 */
	public Usuario(String id, String nombres, String email, String tipoId, String apellidos, String celular,
			String telefono, Departamento departamento, Municipio municipio, String direccion) {
		super();
		this.id = id;
		this.nombres = nombres;
		this.email = email;
		this.tipoId = tipoId;
		this.apellidos = apellidos;
		this.celular = celular;
		this.telefono = telefono;
		this.departamento = departamento;
		this.municipio = municipio;
		this.direccion = direccion;
	}
	/////////////////////////////// get y set ////////////////////////////////////////
	
	/**
	 * devuelve el id
	 * @return el id
	*/
	public String getId() {
		return id;
	}
	/**
	 * modifica el id
	 * @param id el id
	*/
	public void setId(String id) {
		this.id = id;
	}
	/**
	 * devuelve los nombres
	 * @return los nombres
	*/
	public String getNombres() {
		return nombres;
	}
	/**
	 * modifica el nombre
	 * @param nombre el nombre
	*/
	public void setNombres(String nombres) {
		this.nombres = nombres;
	}
	/**
	 * devuelve el email
	 * @return el email
	*/
	public String getEmail() {
		return email;
	}
	/**
	 * modifica el email
	 * @param email el email
	*/
	public void setEmail(String email) {
		this.email = email;
	}
	/**
	 * devuelve el tipo id
	 * @return el tipo id
	*/
	public String getTipoId() {
		return tipoId;
	}
	/**
	 * modifica el tipo id
	 * @param tipoid  el tipo id
	*/
	public void setTipoId(String tipoId) {
		this.tipoId = tipoId;
	}
	/**
	 * devuelve los apellidos
	 * @return los apellidos
	*/
	public String getApellidos() {
		return apellidos;
	}
	/**
	 * modifica el apellido
	 * @param apellido  el apellido
	*/
	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}
	/**
	 * devuelve el celular
	 * @return el celular
	*/
	public String getCelular() {
		return celular;
	}
	/**
	 * modifica el celular
	 * @param celular  el celular
	*/
	public void setCelular(String celular) {
		this.celular = celular;
	}
	/**
	 * devuelve el telefono
	 * @return el telefono
	*/
	public String getTelefono() {
		return telefono;
	}
	/**
	 * modifica el telefono
	 * @param telefono  el telefono
	*/
	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}
	/**
	 * devuelve el departamento
	 * @return el departamento
	*/
	public Departamento getDepartamento() {
		return departamento;
	}
	/**
	 * modifica el departamento
	 * @param departamento  el departamento
	*/
	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}
	/**
	 * devuelve el municipio
	 * @return el municipio
	*/
	public Municipio getMunicipio() {
		return municipio;
	}
	/**
	 * modifica el municipio
	 * @param municipio  el municipio
	*/
	public void setMunicipio(Municipio municipio) {
		this.municipio = municipio;
	}
	/**
	 * devuelve la direccion
	 * @return  la direccion
	*/
	public String getDireccion() {
		return direccion;
	}
	/**
	 * modifica la direccion
	 * @param direccion la direccion
	*/
	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}
	///////////////////////////////string  ////////////////////////////////////////
	
	
	/**
	 * devuelve una string con datos de la clase
	 * @return datos de esta clase
	*/
	@Override
	public String toString() {
		return "Usuario [id=" + id + ", nombres=" + nombres + ", email=" + email + ", tipoId=" + tipoId + ", apellidos="
				+ apellidos + ", celular=" + celular + ", telefono=" + telefono + ", departamento=" + departamento
				+ ", municipio=" + municipio + ", direccion=" + direccion + "]";
	}


	
	
};
