// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Vacunas.mundo;

import java.util.ArrayList;
import java.util.Arrays;

/************************************************************/
/**
 * clase que maneja las eps, los usuarios y la vacunacion
 */
public class Vacunacion {
	/**
	 * lista de las epses
	 */
	private   ArrayList<Eps> epses;
	/**
	 * lista de los departamentos
	 */
	private   ArrayList<Departamento> departamento;

	///////////////////////////////constructor ////////////////////////////////////////
	/**
	 * construye la clase
	 * @param epses lista de epses
	 * @param departamento lista de departamentos
	*/
	public Vacunacion(ArrayList<Eps> epses, ArrayList<Departamento> departamento) {
		super();
		this.epses = epses;
		this.departamento = departamento;
	}
	
	/////////////////////////////// get y set ////////////////////////////////////////
	/**
	 * devuelve la lista de epses
	 * @return la lista de epses
	*/
	public ArrayList<Eps> getEpses() {
		return epses;
	}

	/**
	 * añade epses a la lista de epses
	 * @param eps la eps
	*/
	public void setEpses(Eps epses) {
		this.epses.add(epses);
	}

	/**
	 * devuelve la lista de departamentos
	 * @return la lista de departamentos
	*/
	public ArrayList<Departamento> getDepartamento() {
		return departamento;
	}

	/**
	 * añade departamentos a la lista de departamentos
	 * @param departamento el departamento
	*/
	public void setDepartamento(Departamento departamento) {
		this.departamento.add(departamento);
	}

	///////////////////////////////string  ////////////////////////////////////////

	/**
	 * devuelve una string con datos de la clase
	 * @return datos de esta clase
	*/
	@Override
	public String toString() {
		return "Vacunacion [epses=" + epses + ", departamento=" + departamento + "]";
	}
	
	/**
	 * Elimina un usuario determinado
	 * @param pId identificacion del usuario
	 * @return true si se pudo eliminar al usuario o false si no
	 */
	public boolean eliminarUsuario(String pId) {
		Eps temp = buscarEpsUsuario(pId);
		return temp.eliminarUsuario(pId);
	}

	/**
	 * Busca un usuario en el programa
	 * @param pId id del usuario
	 * @return el usuario buscado o null si no se encontró
	 */
	public Usuario buscarUsuario(String pId) {
		
		Eps temp = buscarEpsUsuario(pId);
		System.out.println(pId);
		System.out.println(temp.getNombre());
		
		return temp.buscarUsuario(pId);
	}

	/**
	 * actualizar un  usuario en el programa
	 * @param pId   identificacion del usuario
	 * @param pNombres   nombres del usuario
	 * @param pEmail    email del usuario
	 * @param pTipoId  tipo de identificacion del usuario
	 * @param pApellidos  apellidos del usuario
	 * @param Pcelular  celular del usuario
	 * @param pTelefono   telefono del usuario
	 * @param pDepartamento   departamento del usuario
	 * @param pMunicipio   municipio del usuario
	 * @param pDireccion   direccion del usuario
	 */
	public void actualizarUsuario(String pId, String pNombres, String pEmail, String pTipoId, String pApellidos,
			String Pcelular, String pTelefono, Departamento pDepartamento, Municipio pMunicipio, String pDireccion) {
		Eps temp = buscarEpsUsuario(pId);
		temp.eliminarUsuario(pId);
		temp.agregarUsuario(pId, pNombres, pEmail, pTipoId, pApellidos, Pcelular, pTelefono, pDepartamento, pMunicipio, pDireccion);
	}


	

	/**
	 * Busca la eps de un usuario determinado
	 * @param pId identificacion del usuario
	 * @return la eps del usuario
	 */
	public Eps buscarEpsUsuario(String pId) {
		//System.out.println( epses.size());
		Eps temporal = null;
		for (int i = 0; i < epses.size(); i++) {
			Eps temp = epses.get(i);
			if(temp.buscarUsuario(pId)!=null) {

				temporal=temp;
				return temporal;
			}
		}
		return temporal;
		
	}
};
